"""initial schema

Revision ID: 00d238ac31b3
Revises: 8dd8a1fb11ae
Create Date: 2025-10-05 19:35:04.230912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d238ac31b3'
down_revision = '8dd8a1fb11ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###