"""initial schema

Revision ID: 042b5a5213a5
Revises: dba8ec5e53eb
Create Date: 2025-10-07 17:36:20.636789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042b5a5213a5'
down_revision = 'dba8ec5e53eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###