"""initial schema

Revision ID: 04fb857a6bb0
Revises: fd6b0d40560a
Create Date: 2025-10-07 17:52:01.892185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04fb857a6bb0'
down_revision = 'fd6b0d40560a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_profiles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_tenant_profiles_is_deleted'), table_name='tenant_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tenant_profiles_is_deleted'), 'tenant_profiles', ['is_deleted'], unique=False)
    op.alter_column('tenant_profiles', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###