"""initial_schema_clean

Revision ID: 1d6c9e43a807
Revises: 4b93027b153b
Create Date: 2025-10-08 14:43:05.942897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6c9e43a807'
down_revision = '4b93027b153b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###