"""initial schema

Revision ID: 1e86f5958452
Revises: 04fb857a6bb0
Create Date: 2025-10-07 23:54:46.539486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e86f5958452'
down_revision = '04fb857a6bb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###