"""initial schema

Revision ID: 2bff9629596d
Revises: 485eda1477ad
Create Date: 2025-10-08 10:25:46.551208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bff9629596d'
down_revision = '485eda1477ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###