"""initial schema

Revision ID: 33cad9a35eb8
Revises: 00d238ac31b3
Create Date: 2025-10-07 10:24:58.521205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cad9a35eb8'
down_revision = '00d238ac31b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###