"""initial schema

Revision ID: 485eda1477ad
Revises: 1e86f5958452
Create Date: 2025-10-07 23:55:04.005348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485eda1477ad'
down_revision = '1e86f5958452'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###