"""initial_schema_clean

Revision ID: 4b93027b153b
Revises: e9d57a7734b8
Create Date: 2025-10-08 10:52:29.075422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b93027b153b'
down_revision = 'e9d57a7734b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###