"""initial schema

Revision ID: 5e803809584a
Revises: 2bff9629596d
Create Date: 2025-10-08 10:33:02.089979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e803809584a'
down_revision = '2bff9629596d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###