"""initial schema

Revision ID: 8dd8a1fb11ae
Revises: f57135693d86
Create Date: 2025-10-05 19:33:37.640230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd8a1fb11ae'
down_revision = 'f57135693d86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###