"""initial schema

Revision ID: dba8ec5e53eb
Revises: ff005f642c60
Create Date: 2025-10-07 17:36:15.867135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba8ec5e53eb'
down_revision = 'ff005f642c60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###