"""initial_schema_clean

Revision ID: e64590d25587
Revises: add_soft_delete_001
Create Date: 2025-10-09 12:23:59.886744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64590d25587'
down_revision = 'add_soft_delete_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###