"""initial_schema_clean

Revision ID: e9d57a7734b8
Revises: 5e803809584a
Create Date: 2025-10-08 10:40:35.688683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d57a7734b8'
down_revision = '5e803809584a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###