"""initial schema

Revision ID: ff005f642c60
Revises: 33cad9a35eb8
Create Date: 2025-10-07 17:32:42.640000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff005f642c60'
down_revision = '33cad9a35eb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('check_in_outs', 'notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_check_in_outs_hostel_id'), table_name='check_in_outs')
    op.drop_index(op.f('idx_check_in_outs_tenant_id'), table_name='check_in_outs')
    op.add_column('tenant_profiles', sa.Column('current_bed_id', sa.Integer(), nullable=True))
    op.alter_column('tenant_profiles', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('tenant_profiles', 'gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'guardian_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'guardian_email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('idx_tenant_profiles_hostel_id'), table_name='tenant_profiles')
    op.drop_index(op.f('idx_tenant_profiles_user_id'), table_name='tenant_profiles')
    op.create_foreign_key(None, 'tenant_profiles', 'beds', ['current_bed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_profiles', type_='foreignkey')
    op.create_index(op.f('idx_tenant_profiles_user_id'), 'tenant_profiles', ['user_id'], unique=False)
    op.create_index(op.f('idx_tenant_profiles_hostel_id'), 'tenant_profiles', ['hostel_id'], unique=False)
    op.alter_column('tenant_profiles', 'guardian_email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'guardian_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('tenant_profiles', 'current_bed_id')
    op.create_index(op.f('idx_check_in_outs_tenant_id'), 'check_in_outs', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_check_in_outs_hostel_id'), 'check_in_outs', ['hostel_id'], unique=False)
    op.alter_column('check_in_outs', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###